openapi: 3.0.0
info:
  title: pos tagger from sentences
  description: Tree tagger
  version: 1.0.0-oas3
paths:
  '/sentences_tagger':
    post:
      operationId: postagger   
      summary: Returns a part of speech for given sentences
      requestBody:
        content:
          application/json:
            schema:
              properties:
                sentences:
                  items:
                    type: string
                  type: array
      responses:
        '200':
          description: A formatted string of the array of sentences of pos tags
          content:
            application/json:
              schema:
                  type: string

