swagger: "2.0"
info:
  title: Suggestion Mining
  description: Models to identify suggestions in text.
  version: "0.1"
  termsOfService: https://nlp.insight-centre.org
  contact:
    name: Sapna Negi
    url: https://nlp.insight-centre.org
    email: firstname.lastname@insight-centre.org
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
host: 0.0.0.0:8001
basePath: /
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  /api:
    x-swagger-router-controller: suggestion_mining
    get:
      description: Return the results
      parameters:
      - name: algo
        default: SuggestionMining
        in: query
        description: defining the algorithm to select suggestion mining
        required: true
        type: string
      - name: i
        in: query
        description: The text input for the service
        required: true
        type: string
      responses:
        '200':
          description: Suggestion mining response
          schema:
            $ref: '#/definitions/SMResponse'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/ErrorResponse'

# complex objects have schema definitions
definitions:
  SMResponse:
    required:
    - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
    - message
    properties:
      message:
        type: string

