site_name: Teanga
nav: 
    - Home: index.md
    - Teanga UI: teanga_ui.md
    - Run Existing Workflow: run_existing_workflow.md
    - Create new Workflow: create_new_workflow.md
theme: material
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

